### ISSUE TITLE
Python.Runtime.PythonException. TypeError : object of type 'generator' has no len()

### ISSUE THREAD

**Issue by joaflores** [AMArostegui/SpacyDotNet#6]
Hola Antonio,

I'm trying tu run the example in the class 'LinguisticFeatures.cs' but I receiving this exception:
Python.Runtime.PythonException. TypeError : object of type 'generator' has no len().

I think this happen when trying to access the 'Children' list member of Token. Because if I try to do a token.Children.Count, same exception arises.
```
foreach (var token in doc.Tokens)
{
    var childs = new List<string>();
    token.Children.ForEach(c => childs.Add(c.Text)); //<---Exception here
    Console.WriteLine($"{token.Text} {token.Dep} {token.Head.Text} [{string.Join(", ", childs)}]");
}  
```
I am running the Test project from Visual Studio 2009 and passing the arguments --interpreter python38.dll --venv 'C:\Users\Jorge\Documents\venv'

**Comment by AMArostegui** [comment]
Yes. There's a bug in that sample. 

Now it's fixed
